# Generated by Django 3.1.5 on 2021-02-04 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fuel_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('efficiency', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='trip_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuelcost.fuel_info')),
            ],
        ),
    ]
