# Generated by Django 3.1.5 on 2021-02-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelcost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel_info',
            name='car',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fuel_info',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
